server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always


spring:
  profiles:
    active: local
  application:
    name: cashonline

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cash_online
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://127.0.0.1:3306
    user: root
    password: 12345678
    schemas: cash_online
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
    hibernate:
      ddl-auto: update

